name: ci-cd.yml
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - run: echo ${{ secrets.DOCKER_USERNAME }} | base64
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
